-- ═══════════════════════════════════════════════════════════════════════════
-- Scelus — Correções de schema (dba_scelus)
-- Aplicado em DEV (posdleg) em 11/07/2026, com round-trip de teste OK em todas
-- as funções (ins -> del). Aplicar em HOMOLOGAÇÃO/PRODUÇÃO junto à equipe de banco.
--
-- Problemas corrigidos:
--   1. PKs de tabelas de domínio sem identity/default — qualquer INSERT sem id
--      explícito (inclusive via fn_*_ins) falhava com not-null violation.
--      Correção: GENERATED BY DEFAULT AS IDENTITY + setval acima do MAX atual.
--   2. As fn_*_ins do pkg_tabela_basica inseriam o parâmetro OUT (nulo) na
--      coluna de ID — quebrava nas tabelas com GENERATED ALWAYS (428C9) e nas
--      sem identity (23502). Correção: INSERT omite a coluna de ID.
--
-- Pendências para a equipe de banco (NÃO corrigidas aqui):
--   - pkg_tabela_basica.fn_prole_ins referencia a tabela public.tb_prole, que
--     não existe (a tabela real é tb_posicao_prole, com estrutura diferente).
--   - pkg_sistema_util.fn_mensagem estava ausente — criada via seed-dev.sql.
-- ═══════════════════════════════════════════════════════════════════════════
ALTER TABLE public.tb_polo ALTER COLUMN int_polo_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_polo', 'int_polo_id'), COALESCE((SELECT MAX(int_polo_id) FROM public.tb_polo), 0) + 1, false);

ALTER TABLE public.tb_estado_civil ALTER COLUMN int_estado_civil_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_estado_civil', 'int_estado_civil_id'), COALESCE((SELECT MAX(int_estado_civil_id) FROM public.tb_estado_civil), 0) + 1, false);

ALTER TABLE public.tb_renda ALTER COLUMN int_renda_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_renda', 'int_renda_id'), COALESCE((SELECT MAX(int_renda_id) FROM public.tb_renda), 0) + 1, false);

ALTER TABLE public.tb_religiao ALTER COLUMN int_religiao_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_religiao', 'int_religiao_id'), COALESCE((SELECT MAX(int_religiao_id) FROM public.tb_religiao), 0) + 1, false);

ALTER TABLE public.tb_raca_etnia ALTER COLUMN int_raca_etnia_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_raca_etnia', 'int_raca_etnia_id'), COALESCE((SELECT MAX(int_raca_etnia_id) FROM public.tb_raca_etnia), 0) + 1, false);

ALTER TABLE public.tb_tipo_vinculo ALTER COLUMN int_tipo_vinculo_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_tipo_vinculo', 'int_tipo_vinculo_id'), COALESCE((SELECT MAX(int_tipo_vinculo_id) FROM public.tb_tipo_vinculo), 0) + 1, false);

ALTER TABLE public.tb_ocupacao ALTER COLUMN int_ocupacao_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_ocupacao', 'int_ocupacao_id'), COALESCE((SELECT MAX(int_ocupacao_id) FROM public.tb_ocupacao), 0) + 1, false);

ALTER TABLE public.tb_deficiencia ALTER COLUMN int_deficiencia_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_deficiencia', 'int_deficiencia_id'), COALESCE((SELECT MAX(int_deficiencia_id) FROM public.tb_deficiencia), 0) + 1, false);

ALTER TABLE public.tb_tipo_comunicante ALTER COLUMN int_tipo_comunicante_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_tipo_comunicante', 'int_tipo_comunicante_id'), COALESCE((SELECT MAX(int_tipo_comunicante_id) FROM public.tb_tipo_comunicante), 0) + 1, false);

ALTER TABLE public.tb_tipo_consequencia_violencia ALTER COLUMN int_tipo_consequencia_violencia_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_tipo_consequencia_violencia', 'int_tipo_consequencia_violencia_id'), COALESCE((SELECT MAX(int_tipo_consequencia_violencia_id) FROM public.tb_tipo_consequencia_violencia), 0) + 1, false);

CREATE OR REPLACE FUNCTION pkg_tabela_basica.fn_polo_ins(p_str_polo character varying, OUT p_int_polo_id bigint, OUT p_resultado character varying)
 RETURNS record
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Inclui polo (correcao: nao insere mais a coluna de ID — gerada por identity)
 		Autor original: Mauro Franca | Correcao: KingJr/PDCase
 		Data correcao: 20260711
 	*/
 DECLARE
 	v_msg		 character varying(500);
 BEGIN
 
     BEGIN
 
 		INSERT INTO public.tb_polo(
 			  str_polo
 			)
 		VALUES (p_str_polo
 			)
 		RETURNING int_polo_id
 		INTO p_int_polo_id;
 
 		p_resultado := pkg_sistema_util.fn_mensagem('GER-S001');
 
     EXCEPTION
 
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
 			p_int_polo_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', v_msg);
 
         WHEN OTHERS THEN
             p_int_polo_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', format('pkg_tabela_basica.fn_polo_ins - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;

CREATE OR REPLACE FUNCTION pkg_tabela_basica.fn_estado_civil_ins(p_str_estado_civil character varying, OUT p_int_estado_civil_id bigint, OUT p_resultado character varying)
 RETURNS record
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Inclui estado_civil (correcao: nao insere mais a coluna de ID — gerada por identity)
 		Autor original: Mauro Franca | Correcao: KingJr/PDCase
 		Data correcao: 20260711
 	*/
 DECLARE
 	v_msg		 character varying(500);
 BEGIN
 
     BEGIN
 
 		INSERT INTO public.tb_estado_civil(
 			  str_estado_civil
 			)
 		VALUES (p_str_estado_civil
 			)
 		RETURNING int_estado_civil_id
 		INTO p_int_estado_civil_id;
 
 		p_resultado := pkg_sistema_util.fn_mensagem('GER-S001');
 
     EXCEPTION
 
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
 			p_int_estado_civil_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', v_msg);
 
         WHEN OTHERS THEN
             p_int_estado_civil_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', format('pkg_tabela_basica.fn_estado_civil_ins - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;

CREATE OR REPLACE FUNCTION pkg_tabela_basica.fn_escolaridade_ins(p_str_escolaridade character varying, OUT p_int_escolaridade_id bigint, OUT p_resultado character varying)
 RETURNS record
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Inclui escolaridade (correcao: nao insere mais a coluna de ID — gerada por identity)
 		Autor original: Mauro Franca | Correcao: KingJr/PDCase
 		Data correcao: 20260711
 	*/
 DECLARE
 	v_msg		 character varying(500);
 BEGIN
 
     BEGIN
 
 		INSERT INTO public.tb_escolaridade(
 			  str_escolaridade
 			)
 		VALUES (p_str_escolaridade
 			)
 		RETURNING int_escolaridade_id
 		INTO p_int_escolaridade_id;
 
 		p_resultado := pkg_sistema_util.fn_mensagem('GER-S001');
 
     EXCEPTION
 
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
 			p_int_escolaridade_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', v_msg);
 
         WHEN OTHERS THEN
             p_int_escolaridade_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', format('pkg_tabela_basica.fn_escolaridade_ins - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;

CREATE OR REPLACE FUNCTION pkg_tabela_basica.fn_renda_ins(p_str_renda character varying, OUT p_int_renda_id bigint, OUT p_resultado character varying)
 RETURNS record
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Inclui renda (correcao: nao insere mais a coluna de ID — gerada por identity)
 		Autor original: Mauro Franca | Correcao: KingJr/PDCase
 		Data correcao: 20260711
 	*/
 DECLARE
 	v_msg		 character varying(500);
 BEGIN
 
     BEGIN
 
 		INSERT INTO public.tb_renda(
 			  str_renda
 			)
 		VALUES (p_str_renda
 			)
 		RETURNING int_renda_id
 		INTO p_int_renda_id;
 
 		p_resultado := pkg_sistema_util.fn_mensagem('GER-S001');
 
     EXCEPTION
 
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
 			p_int_renda_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', v_msg);
 
         WHEN OTHERS THEN
             p_int_renda_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', format('pkg_tabela_basica.fn_renda_ins - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;

CREATE OR REPLACE FUNCTION pkg_tabela_basica.fn_religiao_ins(p_str_religiao character varying, OUT p_int_religiao_id bigint, OUT p_resultado character varying)
 RETURNS record
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Inclui religiao (correcao: nao insere mais a coluna de ID — gerada por identity)
 		Autor original: Mauro Franca | Correcao: KingJr/PDCase
 		Data correcao: 20260711
 	*/
 DECLARE
 	v_msg		 character varying(500);
 BEGIN
 
     BEGIN
 
 		INSERT INTO public.tb_religiao(
 			  str_religiao
 			)
 		VALUES (p_str_religiao
 			)
 		RETURNING int_religiao_id
 		INTO p_int_religiao_id;
 
 		p_resultado := pkg_sistema_util.fn_mensagem('GER-S001');
 
     EXCEPTION
 
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
 			p_int_religiao_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', v_msg);
 
         WHEN OTHERS THEN
             p_int_religiao_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', format('pkg_tabela_basica.fn_religiao_ins - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;

CREATE OR REPLACE FUNCTION pkg_tabela_basica.fn_raca_etnia_ins(p_str_raca_etnia character varying, OUT p_int_raca_etnia_id bigint, OUT p_resultado character varying)
 RETURNS record
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Inclui raca_etnia (correcao: nao insere mais a coluna de ID — gerada por identity)
 		Autor original: Mauro Franca | Correcao: KingJr/PDCase
 		Data correcao: 20260711
 	*/
 DECLARE
 	v_msg		 character varying(500);
 BEGIN
 
     BEGIN
 
 		INSERT INTO public.tb_raca_etnia(
 			  str_raca_etnia
 			)
 		VALUES (p_str_raca_etnia
 			)
 		RETURNING int_raca_etnia_id
 		INTO p_int_raca_etnia_id;
 
 		p_resultado := pkg_sistema_util.fn_mensagem('GER-S001');
 
     EXCEPTION
 
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
 			p_int_raca_etnia_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', v_msg);
 
         WHEN OTHERS THEN
             p_int_raca_etnia_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', format('pkg_tabela_basica.fn_raca_etnia_ins - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;

CREATE OR REPLACE FUNCTION pkg_tabela_basica.fn_situacao_uso_droga_ins(p_str_situacao_uso_droga character varying, OUT p_int_situacao_uso_droga_id bigint, OUT p_resultado character varying)
 RETURNS record
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Inclui situacao_uso_droga (correcao: nao insere mais a coluna de ID — gerada por identity)
 		Autor original: Mauro Franca | Correcao: KingJr/PDCase
 		Data correcao: 20260711
 	*/
 DECLARE
 	v_msg		 character varying(500);
 BEGIN
 
     BEGIN
 
 		INSERT INTO public.tb_situacao_uso_droga(
 			  str_situacao_uso_droga
 			)
 		VALUES (p_str_situacao_uso_droga
 			)
 		RETURNING int_situacao_uso_droga_id
 		INTO p_int_situacao_uso_droga_id;
 
 		p_resultado := pkg_sistema_util.fn_mensagem('GER-S001');
 
     EXCEPTION
 
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
 			p_int_situacao_uso_droga_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', v_msg);
 
         WHEN OTHERS THEN
             p_int_situacao_uso_droga_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', format('pkg_tabela_basica.fn_situacao_uso_droga_ins - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;

-- ── Correção pkg_fato_ocorrido.fn_fato_ocorrido_del (removido delete de tb_consequencia_violencia) ──
CREATE OR REPLACE FUNCTION pkg_fato_ocorrido.fn_fato_ocorrido_del(p_int_fato_ocorrido_id bigint, OUT p_resultado character varying)
 RETURNS character varying
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Exclui Fato Ocorrido (corrigido: removido delete de tb_consequencia_violencia que não possui coluna int_fato_ocorrido_id)
 		Autor original: Mauro França | Correções: Antonio Júnior
 		Data: 20260712
 	*/
 DECLARE 
 	v_msg		  		character varying(500);
 BEGIN
     BEGIN
 		delete 
 			from public.tb_fato_ocorrido_comunicante
 		where int_fato_ocorrido_id = p_int_fato_ocorrido_id;
 
 		delete 
 			from public.tb_medida_protetiva_urgencia
 		where int_mpu_id in (Select int_mpu_id 
 		                       from public.tb_fato_ocorrido_mpu
 		                       where int_fato_ocorrido_id = p_int_fato_ocorrido_id);
 		
 		delete 
 			from public.tb_fato_ocorrido_mpu
 		where int_fato_ocorrido_id = p_int_fato_ocorrido_id;		
 
 	    DELETE 
 		  FROM public.tb_fato_ocorrido
 			WHERE int_fato_ocorrido_id = p_int_fato_ocorrido_id;
 	
         IF NOT FOUND THEN
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E999','Registro não encontrado para exclusão.');
             RETURN;
         END IF;
 		
         p_resultado := pkg_sistema_util.fn_mensagem('GER-S003');
 
     EXCEPTION
 	    WHEN SQLSTATE 'P0099' THEN
 			p_resultado:= pkg_sistema_util.fn_mensagem('GER-E003', v_msg);
 			
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E003', v_msg);
 			
         WHEN OTHERS THEN
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E003', format('pkg_fato_ocorrido.fn_fato_ocorrido_del - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;
