-- ═══════════════════════════════════════════════════════════════════════════
-- Scelus — Correções de schema (dba_scelus)
-- Aplicado em DEV (posdleg) em 11/07/2026, com round-trip de teste OK em todas
-- as funções (ins -> del). Aplicar em HOMOLOGAÇÃO/PRODUÇÃO junto à equipe de banco.
--
-- Problemas corrigidos:
--   1. PKs de tabelas de domínio sem identity/default — qualquer INSERT sem id
--      explícito (inclusive via fn_*_ins) falhava com not-null violation.
--      Correção: GENERATED BY DEFAULT AS IDENTITY + setval acima do MAX atual.
--   2. As fn_*_ins do pkg_tabela_basica inseriam o parâmetro OUT (nulo) na
--      coluna de ID — quebrava nas tabelas com GENERATED ALWAYS (428C9) e nas
--      sem identity (23502). Correção: INSERT omite a coluna de ID.
--
-- Pendências para a equipe de banco (NÃO corrigidas aqui):
--   - pkg_tabela_basica.fn_prole_ins referencia a tabela public.tb_prole, que
--     não existe (a tabela real é tb_posicao_prole, com estrutura diferente).
--   - pkg_sistema_util.fn_mensagem estava ausente — criada via seed-dev.sql.
-- ═══════════════════════════════════════════════════════════════════════════
ALTER TABLE public.tb_polo ALTER COLUMN int_polo_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_polo', 'int_polo_id'), COALESCE((SELECT MAX(int_polo_id) FROM public.tb_polo), 0) + 1, false);

ALTER TABLE public.tb_estado_civil ALTER COLUMN int_estado_civil_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_estado_civil', 'int_estado_civil_id'), COALESCE((SELECT MAX(int_estado_civil_id) FROM public.tb_estado_civil), 0) + 1, false);

ALTER TABLE public.tb_renda ALTER COLUMN int_renda_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_renda', 'int_renda_id'), COALESCE((SELECT MAX(int_renda_id) FROM public.tb_renda), 0) + 1, false);

ALTER TABLE public.tb_religiao ALTER COLUMN int_religiao_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_religiao', 'int_religiao_id'), COALESCE((SELECT MAX(int_religiao_id) FROM public.tb_religiao), 0) + 1, false);

ALTER TABLE public.tb_raca_etnia ALTER COLUMN int_raca_etnia_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_raca_etnia', 'int_raca_etnia_id'), COALESCE((SELECT MAX(int_raca_etnia_id) FROM public.tb_raca_etnia), 0) + 1, false);

ALTER TABLE public.tb_tipo_vinculo ALTER COLUMN int_tipo_vinculo_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_tipo_vinculo', 'int_tipo_vinculo_id'), COALESCE((SELECT MAX(int_tipo_vinculo_id) FROM public.tb_tipo_vinculo), 0) + 1, false);

ALTER TABLE public.tb_ocupacao ALTER COLUMN int_ocupacao_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_ocupacao', 'int_ocupacao_id'), COALESCE((SELECT MAX(int_ocupacao_id) FROM public.tb_ocupacao), 0) + 1, false);

ALTER TABLE public.tb_deficiencia ALTER COLUMN int_deficiencia_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_deficiencia', 'int_deficiencia_id'), COALESCE((SELECT MAX(int_deficiencia_id) FROM public.tb_deficiencia), 0) + 1, false);

ALTER TABLE public.tb_tipo_comunicante ALTER COLUMN int_tipo_comunicante_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_tipo_comunicante', 'int_tipo_comunicante_id'), COALESCE((SELECT MAX(int_tipo_comunicante_id) FROM public.tb_tipo_comunicante), 0) + 1, false);

ALTER TABLE public.tb_tipo_consequencia_violencia ALTER COLUMN int_tipo_consequencia_violencia_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('public.tb_tipo_consequencia_violencia', 'int_tipo_consequencia_violencia_id'), COALESCE((SELECT MAX(int_tipo_consequencia_violencia_id) FROM public.tb_tipo_consequencia_violencia), 0) + 1, false);

CREATE OR REPLACE FUNCTION pkg_tabela_basica.fn_polo_ins(p_str_polo character varying, OUT p_int_polo_id bigint, OUT p_resultado character varying)
 RETURNS record
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Inclui polo (correcao: nao insere mais a coluna de ID — gerada por identity)
 		Autor original: Mauro Franca | Correcao: KingJr/PDCase
 		Data correcao: 20260711
 	*/
 DECLARE
 	v_msg		 character varying(500);
 BEGIN
 
     BEGIN
 
 		INSERT INTO public.tb_polo(
 			  str_polo
 			)
 		VALUES (p_str_polo
 			)
 		RETURNING int_polo_id
 		INTO p_int_polo_id;
 
 		p_resultado := pkg_sistema_util.fn_mensagem('GER-S001');
 
     EXCEPTION
 
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
 			p_int_polo_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', v_msg);
 
         WHEN OTHERS THEN
             p_int_polo_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', format('pkg_tabela_basica.fn_polo_ins - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;

CREATE OR REPLACE FUNCTION pkg_tabela_basica.fn_estado_civil_ins(p_str_estado_civil character varying, OUT p_int_estado_civil_id bigint, OUT p_resultado character varying)
 RETURNS record
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Inclui estado_civil (correcao: nao insere mais a coluna de ID — gerada por identity)
 		Autor original: Mauro Franca | Correcao: KingJr/PDCase
 		Data correcao: 20260711
 	*/
 DECLARE
 	v_msg		 character varying(500);
 BEGIN
 
     BEGIN
 
 		INSERT INTO public.tb_estado_civil(
 			  str_estado_civil
 			)
 		VALUES (p_str_estado_civil
 			)
 		RETURNING int_estado_civil_id
 		INTO p_int_estado_civil_id;
 
 		p_resultado := pkg_sistema_util.fn_mensagem('GER-S001');
 
     EXCEPTION
 
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
 			p_int_estado_civil_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', v_msg);
 
         WHEN OTHERS THEN
             p_int_estado_civil_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', format('pkg_tabela_basica.fn_estado_civil_ins - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;

CREATE OR REPLACE FUNCTION pkg_tabela_basica.fn_escolaridade_ins(p_str_escolaridade character varying, OUT p_int_escolaridade_id bigint, OUT p_resultado character varying)
 RETURNS record
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Inclui escolaridade (correcao: nao insere mais a coluna de ID — gerada por identity)
 		Autor original: Mauro Franca | Correcao: KingJr/PDCase
 		Data correcao: 20260711
 	*/
 DECLARE
 	v_msg		 character varying(500);
 BEGIN
 
     BEGIN
 
 		INSERT INTO public.tb_escolaridade(
 			  str_escolaridade
 			)
 		VALUES (p_str_escolaridade
 			)
 		RETURNING int_escolaridade_id
 		INTO p_int_escolaridade_id;
 
 		p_resultado := pkg_sistema_util.fn_mensagem('GER-S001');
 
     EXCEPTION
 
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
 			p_int_escolaridade_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', v_msg);
 
         WHEN OTHERS THEN
             p_int_escolaridade_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', format('pkg_tabela_basica.fn_escolaridade_ins - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;

CREATE OR REPLACE FUNCTION pkg_tabela_basica.fn_renda_ins(p_str_renda character varying, OUT p_int_renda_id bigint, OUT p_resultado character varying)
 RETURNS record
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Inclui renda (correcao: nao insere mais a coluna de ID — gerada por identity)
 		Autor original: Mauro Franca | Correcao: KingJr/PDCase
 		Data correcao: 20260711
 	*/
 DECLARE
 	v_msg		 character varying(500);
 BEGIN
 
     BEGIN
 
 		INSERT INTO public.tb_renda(
 			  str_renda
 			)
 		VALUES (p_str_renda
 			)
 		RETURNING int_renda_id
 		INTO p_int_renda_id;
 
 		p_resultado := pkg_sistema_util.fn_mensagem('GER-S001');
 
     EXCEPTION
 
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
 			p_int_renda_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', v_msg);
 
         WHEN OTHERS THEN
             p_int_renda_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', format('pkg_tabela_basica.fn_renda_ins - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;

CREATE OR REPLACE FUNCTION pkg_tabela_basica.fn_religiao_ins(p_str_religiao character varying, OUT p_int_religiao_id bigint, OUT p_resultado character varying)
 RETURNS record
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Inclui religiao (correcao: nao insere mais a coluna de ID — gerada por identity)
 		Autor original: Mauro Franca | Correcao: KingJr/PDCase
 		Data correcao: 20260711
 	*/
 DECLARE
 	v_msg		 character varying(500);
 BEGIN
 
     BEGIN
 
 		INSERT INTO public.tb_religiao(
 			  str_religiao
 			)
 		VALUES (p_str_religiao
 			)
 		RETURNING int_religiao_id
 		INTO p_int_religiao_id;
 
 		p_resultado := pkg_sistema_util.fn_mensagem('GER-S001');
 
     EXCEPTION
 
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
 			p_int_religiao_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', v_msg);
 
         WHEN OTHERS THEN
             p_int_religiao_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', format('pkg_tabela_basica.fn_religiao_ins - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;

CREATE OR REPLACE FUNCTION pkg_tabela_basica.fn_raca_etnia_ins(p_str_raca_etnia character varying, OUT p_int_raca_etnia_id bigint, OUT p_resultado character varying)
 RETURNS record
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Inclui raca_etnia (correcao: nao insere mais a coluna de ID — gerada por identity)
 		Autor original: Mauro Franca | Correcao: KingJr/PDCase
 		Data correcao: 20260711
 	*/
 DECLARE
 	v_msg		 character varying(500);
 BEGIN
 
     BEGIN
 
 		INSERT INTO public.tb_raca_etnia(
 			  str_raca_etnia
 			)
 		VALUES (p_str_raca_etnia
 			)
 		RETURNING int_raca_etnia_id
 		INTO p_int_raca_etnia_id;
 
 		p_resultado := pkg_sistema_util.fn_mensagem('GER-S001');
 
     EXCEPTION
 
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
 			p_int_raca_etnia_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', v_msg);
 
         WHEN OTHERS THEN
             p_int_raca_etnia_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', format('pkg_tabela_basica.fn_raca_etnia_ins - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;

CREATE OR REPLACE FUNCTION pkg_tabela_basica.fn_situacao_uso_droga_ins(p_str_situacao_uso_droga character varying, OUT p_int_situacao_uso_droga_id bigint, OUT p_resultado character varying)
 RETURNS record
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Inclui situacao_uso_droga (correcao: nao insere mais a coluna de ID — gerada por identity)
 		Autor original: Mauro Franca | Correcao: KingJr/PDCase
 		Data correcao: 20260711
 	*/
 DECLARE
 	v_msg		 character varying(500);
 BEGIN
 
     BEGIN
 
 		INSERT INTO public.tb_situacao_uso_droga(
 			  str_situacao_uso_droga
 			)
 		VALUES (p_str_situacao_uso_droga
 			)
 		RETURNING int_situacao_uso_droga_id
 		INTO p_int_situacao_uso_droga_id;
 
 		p_resultado := pkg_sistema_util.fn_mensagem('GER-S001');
 
     EXCEPTION
 
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
 			p_int_situacao_uso_droga_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', v_msg);
 
         WHEN OTHERS THEN
             p_int_situacao_uso_droga_id := NULL;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E001', format('pkg_tabela_basica.fn_situacao_uso_droga_ins - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;

-- ── Correção pkg_fato_ocorrido.fn_fato_ocorrido_del (removido delete de tb_consequencia_violencia) ──
CREATE OR REPLACE FUNCTION pkg_fato_ocorrido.fn_fato_ocorrido_del(p_int_fato_ocorrido_id bigint, OUT p_resultado character varying)
 RETURNS character varying
 LANGUAGE plpgsql
 AS $function$
 	/*
 		Exclui Fato Ocorrido (corrigido: removido delete de tb_consequencia_violencia que não possui coluna int_fato_ocorrido_id)
 		Autor original: Mauro França | Correções: Antonio Júnior
 		Data: 20260712
 	*/
 DECLARE 
 	v_msg		  		character varying(500);
 BEGIN
     BEGIN
 		delete 
 			from public.tb_fato_ocorrido_comunicante
 		where int_fato_ocorrido_id = p_int_fato_ocorrido_id;
 
 		delete 
 			from public.tb_medida_protetiva_urgencia
 		where int_mpu_id in (Select int_mpu_id 
 		                       from public.tb_fato_ocorrido_mpu
 		                       where int_fato_ocorrido_id = p_int_fato_ocorrido_id);
 		
 		delete 
 			from public.tb_fato_ocorrido_mpu
 		where int_fato_ocorrido_id = p_int_fato_ocorrido_id;		
 
 	    DELETE 
 		  FROM public.tb_fato_ocorrido
 			WHERE int_fato_ocorrido_id = p_int_fato_ocorrido_id;
 	
         IF NOT FOUND THEN
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E999','Registro não encontrado para exclusão.');
             RETURN;
         END IF;
 		
         p_resultado := pkg_sistema_util.fn_mensagem('GER-S003');
 
     EXCEPTION
 	    WHEN SQLSTATE 'P0099' THEN
 			p_resultado:= pkg_sistema_util.fn_mensagem('GER-E003', v_msg);
 			
         WHEN SQLSTATE 'P0001' THEN
 		    GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E003', v_msg);
 			
         WHEN OTHERS THEN
             p_resultado := pkg_sistema_util.fn_mensagem('GER-E003', format('pkg_fato_ocorrido.fn_fato_ocorrido_del - Mensagem de erro: %s (%s).', SQLERRM, SQLSTATE));
 
     END;
 END;
 $function$;

-- ── Nova função pkg_processo.fn_processo_assunto_pje_con (Tela 2.1 do CSU002 — assuntos do processo via PJe) ──
CREATE OR REPLACE FUNCTION pkg_processo.fn_processo_assunto_pje_con(p_int_processo_id integer)
RETURNS TABLE(int_codigo_assunto integer, str_descricao_assunto character varying)
LANGUAGE plpgsql
AS $function$

	/*
		Vai no PJE e retorna os assuntos vinculados ao processo para uso do Sistema SCELUS

		Autor: Fco Antonio S. Júnior - PDCase
		Data: 20260713
	*/

declare
    v_sql text;
begin

    v_sql := '
        select ass.cd_assunto_trf as int_codigo_assunto,
               ass.ds_assunto_trf as str_descricao_assunto
        from client.tb_processo_assunto prcass
        left join client.tb_assunto_trf ass on prcass.id_assunto_trf = ass.id_assunto_trf
        where prcass.id_processo_trf = ' || quote_nullable(p_int_processo_id) || '
        order by ass.ds_assunto_trf
    ';

    return query
    select *
    from dblink(
        'pje',
        v_sql
    ) as t (
        int_codigo_assunto integer,
        str_descricao_assunto character varying
    );

end;
$function$;

-- ── Nova coluna tb_processo_crime.str_descricao_assunto (CSU001 — coluna "Crime" com descrição, não só código) ──
ALTER TABLE public.tb_processo_crime
ADD COLUMN IF NOT EXISTS str_descricao_assunto character varying;

-- ── Correção pkg_litigancia.fn_litigancia_con — 5 bugs (só se manifestam em runtime, pois PL/pgSQL
-- não valida a SQL interna do RETURN QUERY na criação da função; cada bug só aparece depois que o
-- anterior é corrigido, pois a execução aborta no primeiro problema encontrado) ──
--   1. p_str_numero_unico declarado bigint, mas comparado com l.str_numero_unico (varchar) — causava
--      "operator does not exist: character varying = bigint" em toda chamada (GET /crimes/{id}/completo),
--      mesmo com o parâmetro NULL (curto-circuito do OR não evita a checagem de tipo em tempo de planejamento).
--      Correção: tipo do parâmetro alterado para character varying.
--   2. "rec_basel.int_escolaridade_id" — typo, a subquery se chama "rec_base" (sem o "l" no final).
--   3. "v.int_posicao" — alias "v" não existe no FROM; a coluna é "rec_base.int_posicao".
--   4. "ORDER BY rec_base.int_inscricao_id" — coluna não existe em rec_base (nenhuma coluna com esse
--      nome é selecionada na subquery); trocado para rec_base.int_litigancia_id, seguindo o padrão de
--      outras fn_*_con que ordenam a paginação pela PK da tabela principal.
--   5. "'???' as str_parte" — literal sem cast é inferido como "text" pelo Postgres, mas a coluna
--      de retorno é "character varying" — "structure of query does not match function result type"
--      na coluna 6. Correção: '???'::character varying.
--
-- Nota (14/07): ao aplicar a correção do bug 1 em DEV via CREATE OR REPLACE, o Postgres não substituiu
-- a função antiga — mudar o tipo de um parâmetro de entrada cria uma assinatura diferente (overload),
-- não uma substituição. Foi necessário localizar e remover manualmente o overload antigo
-- (DROP FUNCTION pkg_litigancia.fn_litigancia_con(bigint, bigint, bigint, bigint, integer, integer))
-- antes de reaplicar. Quem for aplicar este script do zero num ambiente que já tenha a versão antiga
-- deve verificar se não sobrou overload duplicado (SELECT ... FROM pg_proc WHERE proname = 'fn_litigancia_con').
CREATE OR REPLACE FUNCTION pkg_litigancia.fn_litigancia_con(p_int_litigancia_id bigint DEFAULT NULL::bigint, p_int_polo_id bigint DEFAULT NULL::bigint, p_str_numero_unico character varying DEFAULT NULL::character varying, p_int_parte_id bigint DEFAULT NULL::bigint, p_int_start_row integer DEFAULT NULL::integer, p_int_end_row integer DEFAULT NULL::integer)
 RETURNS TABLE(int_litigancia_id bigint, int_polo_id bigint, str_polo character varying, str_numero_unico character varying, int_parte_id bigint, str_parte character varying, int_situacao_uso_droga_id bigint, str_situacao_uso_droga character varying, int_estado_civil_id bigint, str_estado_civil character varying, int_escolaridade_id bigint, str_escolaridade character varying, int_renda_id bigint, str_renda character varying, int_religiao_id bigint, str_religiao character varying, int_posicao_prole_id bigint, int_prole bigint, int_posicao bigint, int_raca_etnia_id bigint, str_raca_etnia character varying, str_observacoes_posicao_prole character varying, int_reg bigint, int_total_count bigint)
 LANGUAGE plpgsql
AS $function$

	/*
		Consulta Litigancia
		Autor: Mauro França
		Solicitante: KingJr
		Data criação: 20260605
	*/

DECLARE
    v_tamanho_pagina integer;
    v_inicio_pagina  integer;
BEGIN
    -- Paginação...
    v_inicio_pagina :=
        CASE
            WHEN p_int_start_row = 0 THEN 1
            WHEN p_int_start_row IS NOT NULL THEN p_int_start_row
            ELSE 1
        END;

    v_tamanho_pagina :=
        CASE
            WHEN p_int_end_row IS NOT NULL THEN p_int_end_row
            ELSE 99999
        END;

    -- converte start/end row para OFFSET/LIMIT
    v_inicio_pagina  := v_inicio_pagina - 1;
    v_tamanho_pagina := v_tamanho_pagina - v_inicio_pagina;

    RETURN QUERY
    SELECT
			  rec_base.int_litigancia_id
			, rec_base.int_polo_id
			, rec_base.str_polo
			, rec_base.str_numero_unico
			, rec_base.int_parte_id
			, rec_base.str_parte
			, rec_base.int_situacao_uso_droga_id
			, rec_base.str_situacao_uso_droga
			, rec_base.int_estado_civil_id
			, rec_base.str_estado_civil
			, rec_base.int_escolaridade_id
			, rec_base.str_escolaridade
			, rec_base.int_renda_id
			, rec_base.str_renda
			, rec_base.int_religiao_id
			, rec_base.str_religiao
			, rec_base.int_posicao_prole_id
			, rec_base.int_prole
			, rec_base.int_posicao
			, rec_base.int_raca_etnia_id
			, rec_base.str_raca_etnia
			, rec_base.str_observacoes_posicao_prole,
        ROW_NUMBER() OVER (ORDER BY rec_base.int_litigancia_id DESC) AS int_reg,
        COUNT(*) OVER () AS  int_total_count
    FROM (
			SELECT l.int_litigancia_id
			     , l.int_polo_id
				 , p.str_polo
				 , l.str_numero_unico
				 , l.int_parte_id
			     , '???'::character varying as str_parte
				 , l.int_situacao_uso_droga_id
				 , sud.str_situacao_uso_droga
				 , l.int_estado_civil_id
				 , ec.str_estado_civil
				 , l.int_escolaridade_id
				 , e.str_escolaridade
				 , l.int_renda_id
				 , re.str_renda
				 , l.int_religiao_id
				 , rl.str_religiao
				 , l.int_posicao_prole_id
				 , pp.int_prole
				 , pp.int_posicao
				 , l.int_raca_etnia_id
				 , ret.str_raca_etnia
				 , l.str_observacoes_posicao_prole
			FROM public.tb_litigancia l
			left join tb_polo p on l.int_polo_id = p.int_polo_id
			--left join vw_parte
			left join public.tb_situacao_uso_droga sud on l.int_situacao_uso_droga_id = sud.int_situacao_uso_droga_id
			left join public.tb_estado_civil ec on l.int_estado_civil_id = ec.int_estado_civil_id
			left join public.tb_escolaridade e on l.int_escolaridade_id = e.int_escolaridade_id
			left join public.tb_renda re on l.int_renda_id = re.int_renda_id
			left join public.tb_religiao rl on l.int_religiao_id = rl.int_religiao_id
			left join public.tb_posicao_prole pp on l.int_posicao_prole_id = pp.int_posicao_prole_id
			left join public.tb_raca_etnia ret on l.int_raca_etnia_id = ret.int_raca_etnia_id

			where
            1=1
			  and (p_int_litigancia_id is null or l.int_litigancia_id = p_int_litigancia_id)
			  and (p_int_polo_id is null or l.int_polo_id = p_int_polo_id)
			  and (p_str_numero_unico is null or l.str_numero_unico = p_str_numero_unico)
			  and (p_int_parte_id is null or l.int_parte_id = p_int_parte_id)
    ) rec_base
    LIMIT v_tamanho_pagina
    OFFSET v_inicio_pagina;

END;
$function$;
